#ifndef COMPUTATIONAL_GRAPH_ADVANCED_CALC_PACK_H
#define COMPUTATIONAL_GRAPH_ADVANCED_CALC_PACK_H
#include "sincnode.h"
#include "tanhcnode.h"
#include "logcnode.h"
#include "expcnode.h"
#include "sigcnode.h"
#include "assignnode.h"
#include "relucnode.h"
#include "softmax.h"
#include "gradcnode.h"
#include "gradnode.h"
#endif //COMPUTATIONAL_GRAPH_ADVANCED_CALC_PACK_H
